name: Scheduled build
on:
  schedule:
    # 월화수목금 9~18시에 한시간마다 실행
    # UTC의 09:00는 한국시간 18:00
    - cron: '0 9-17/1 * * 1-5'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X GET "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=FSLY&apikey=${{ secrets.API_KEY }}"
        #run: curl --show-error -X POST -d {} "${{ secrets.BUILD_HOOK_URL }}"
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Hello, Slack!
